language: generic
sudo: required

services:
  - docker


before_install:
  - docker build -t kaushalsaurabh/docker -f Dockerfile.dev .

script:
  - docker run -e CI=true kaushalsaurabh/docker npm run test


